server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/account-service}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

jwt:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
  expiration: 2h
  issuer: account-service