eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    org.springframework.cloud: DEBUG