server:
  port: 0

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://account-service/.well-known/jwks.json

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 2s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task-service}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:"localhost:9092"}
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.arsnyan.*
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.arsnyan.taskmanagementservice.model.message.UserEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topics:
      user_events: user_events
    consumer:
      concurrency: 3
      retry:
        max-attempts: 3
        backoff-ms: 1000

  email:
    motivational-quote: "Keep up with the good work!"
    cta-url: ""
    unsubscribe-url: ""
    preferences-url: ""

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html