spring:
  application:
    name: account-service
  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://config-service:8888
      fail-fast: true

app:
  email:
    welcome-user-registered-path: http://config-service:8888/templates/welcome-user-registered.html