server:
  port: 8888

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO
    org.springframework.cloud: DEBUG

spring:
  profiles:
    active: git
  cloud:
    refresh:
      enabled: false
    config:
      server:
        git:
          uri: https://github.com/arsnyan/task-tracker
          search-paths: service-configs